homepage: "https://www.r-project.org/"
language: c
primary_contact: "kevin@posit.co"
main_repo: "https://svn.r-project.org/R/trunk"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
  - afl
