homepage: "https://facebook.github.io/zstd/"
language: c++
primary_contact: "yann.collet.73@gmail.com"
main_repo: "https://github.com/facebook/zstd.git"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
