homepage: "https://www.cups.org/"
language: c
primary_contact: "msweet@msweet.org"
main_repo: "https://github.com/apple/cups"
sanitizers:
  - address
  - memory
  - undefined
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
architectures:
  - x86_64
