homepage: "https://github.com/opencontainers/runc"
language: go
primary_contact: "security@opencontainers.org"
main_repo: "https://github.com/opencontainers/runc"
sanitizers: [address, memory]
fuzzing_engines: [libfuzzer]
