homepage: "https://www.hyperledger.org"
main_repo: "https://github.com/hyperledger/fabric"
primary_contact: ""
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
