homepage: "https://github.com/google/go-github"
language: go
main_repo: "https://github.com/google/go-github"
primary_contact: "glenn@on-demand-books.com"
auto_ccs:
  - "glenn@on-demand-books.com"
  - "youichi0929@outlook.jp"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
