homepage: https://xenproject.org
language: c
main_repo: "https://github.com/xen-project/xen"
auto_ccs:
  - "tamas.k.lengyel@gmail.com"
  - "jbeulich@suse.com"
  - "andrew.cooper@cloud.com"
  - "roger.pau@cloud.com"
  - "sstabellini@kernel.org"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
