base_os_version: ubuntu-24-04
homepage: "https://www.gnu.org/s/libmicrohttpd/"
main_repo: "https://github.com/Karlson2k/libmicrohttpd"
primary_contact: "grothoff@gmail.com"
language: c
vendor_ccs:
  - "arthur.chan@adalogics.com"
  - "david@adalogics.com"
  - "adam@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
architectures:
  - x86_64
builds_per_day: 1
