homepage: https://crates.io/crates/arm-ffa
language: rust
primary_contact: Sandrine.Afsa@arm.com
auto_ccs:
  - Balint.Dobszay@arm.com
  - Baltazar.Radics@arm.com
  - Gergely.Balint@arm.com
  - Gyorgy.Szing@arm.com
  - Imre.Kis@arm.com
  - Olivier.Deprez@arm.com
main_repo: https://git.trustedfirmware.org/arm-firmware-crates/arm-ffa.git
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
coverage_extra_args: --ignore-filename-regex='/rust/'
