homepage: "https://github.com/ruby/json"
language: ruby
primary_contact: "jean.boussier@gmail.com"
auto_ccs:
  - "tranquac0312@gmail.com"
main_repo: "https://github.com/ruby/json"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
