homepage: "https://www.pidgin.im/"
primary_contact: "gary.kramlich@gmail.com"
language: c
auto_ccs:
  - "quantum.analyst@gmail.com"
  - "rekkanoryo.guifications@gmail.com"
main_repo: "https://github.com/pidgin/pidgin"

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

