homepage: https://gitlab.gnome.org/GNOME/gdk-pixbuf/
language: c
primary_contact: ebassi@gnome.org
sanitizers:
  - address
  - undefined
main_repo: "https://github.com/GNOME/gdk-pixbuf"

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

