homepage: "https://github.com/python-poetry/tomlkit"
language: python
primary_contact: "sdispater@gmail.com" # Main author email / poetry maintainers
auto_ccs:
  - "sajjadrahimnouri@gmail.com"
sanitizers:
  - address
  - undefined
