homepage: "https://github.com/puma/puma"
language: ruby
primary_contact: "nate.berkopec@gmail.com"
auto_ccs:
  - "tranquac0312@gmail.com"
main_repo: "https://github.com/puma/puma"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
