homepage: "https://github.com/spf13/cobra
go-chi/chi"
language: go
primary_contact: "security@spf13.com
go-chi.com"
main_repo: "https://github.com/spf13/cobra
go-chi/chi"
sanitizers: [address, memory]
fuzzing_engines: [libfuzzer]
