fuzzing_engines:
- libfuzzer
homepage: https://onnx.ai/
language: python
main_repo: https://github.com/onnx/onnx
primary_contact: onnx-technical-discuss@lists.lfaidata.foundation
sanitizers:
- address
- undefined
