fuzzing_engines:
- libfuzzer
homepage: https://onnx.ai/
language: python
main_repo: https://github.com/onnx/onnx
primary_contact: a.fehlner@googlemail.com
auto_ccs:
  - fehlner@arcor.de
sanitizers:
- address
- undefined
