homepage: "https://github.com/google/jimfs"
language: jvm
main_repo: "https://github.com/google/jimfs"
primary_contact: "cgdecker@google.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
  - "yakdan@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "jacek.trossen@code-intelligence.com"
