homepage: "https://github.com/huggingface/safetensors"
language: rust
main_repo: "https://github.com/huggingface/safetensors"
primary_contact: "ahkarl13@gmail.com"
auto_ccs:
  - "ahkarl13@gmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
architectures:
  - x86_64
