homepage: "https://github.com/bytecodealliance/wasmtime"
language: rust
primary_contact: "security@rust-lang.org"
main_repo: "https://github.com/bytecodealliance/wasmtime"
sanitizers: [address]
fuzzing_engines: [libfuzzer]
