homepage: "https://github.com/openbmc/estoraged"
language: c++
primary_contact: "pedroysb@google.com"
auto_ccs:
  - "pedroysb@google.com"
  - "cloud-ti-fuzzing+bugs@google.com"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/openbmc/estoraged"
