homepage: "https://github.com/protocolbuffers/protobuf"
language: c++
primary_contact: "protobuf-oss-fuzz@google.com"
auto_ccs:
  - "protobuf-team@google.com"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
architectures:
  - x86_64
