homepage: "https://github.com/psf/requests"
language: python
primary_contact: "security@python.org"
main_repo: "https://github.com/psf/requests"
sanitizers: [address, undefined]
fuzzing_engines: [libfuzzer]
