homepage: "https://pypy.org/"
language: c
main_repo: "https://github.com/pypy/pypy"
auto_ccs:
 - "stanulbrych@gmail.com"
 - "matti.picus@gmail.com"
 - "cfbolz@gmail.com"
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
sanitizers:
 - undefined
