homepage: "https://juliastrings.github.io/utf8proc/"
language: c++
primary_contact: "stevenj@mit.edu"
main_repo: "https://github.com/JuliaStrings/utf8proc.git"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
