base_os_version: ubuntu-24-04
homepage: "https://scorecard.dev/"
main_repo: "https://github.com/ossf/scorecard"
# Maintainers: https://github.com/ossf/scorecard/blob/main/MAINTAINERS.md
primary_contact: "hey@auggie.dev"
auto_ccs:
  - adam@adalogics.com
  - jlm@jlm.name
  - sschrock@google.com
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
