homepage: "https://xerces.apache.org/index.html"
language: jvm
main_repo: "https://github.com/apache/xerces2-j"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
  - "yakdan@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "jacek.trossen@code-intelligence.com"
