homepage: "https://www.vim.org/"
main_repo: "https://github.com/vim/vim"
language: c
primary_contact: "vim-dev@vim.org"
auto_ccs:
  - "vim-dev@vim.org"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
