homepage: "https://openvpn.net/"
language: c
primary_contact: "openvpn-security@openvpn.net"
main_repo: "https://github.com/OpenVPN/openvpn"
sanitizers:
  - address
  - memory
  - undefined
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
architectures:
  - x86_64
