homepage: "https://github.com/leethomason/tinyxml2"
language: c++
primary_contact: "leethomason@gmail.com"
main_repo: "https://github.com/leethomason/tinyxml2.git"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
