homepage: "https://github.com/NguyenHien-8/TCQ-Network-Protocol"
language: go
primary_contact: "trannguyenhien29085@gmail.com"
main_repo: "https://github.com/NguyenHien-8/TCQ-Network-Protocol"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
