homepage: "https://github.com/python-openxml/python-docx"
main_repo: "https://github.com/python-openxml/python-docx"
language: python
primary_contact: "sajjadrahimnouri@gmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined