homepage: "https://github.com/russellhaering/goxmldsig"
language: go
main_repo: "https://github.com/russellhaering/goxmldsig"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
primary_contact: "russellhaering@gmail.com"
