homepage: "https://github.com/ibireme/yyjson"
language: c++
primary_contact: "ibireme@gmail.com"
main_repo: "https://github.com/ibireme/yyjson.git"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
