# OSS-Fuzz project descriptor for go-seccure.

homepage: "https://github.com/invenity-labs/go-seccure"
language: go
primary_contact: "imdaveb@gmail.com"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/invenity-labs/go-seccure"
file_github_issue: true
