homepage: "https://formatjs.github.io/"
language: javascript
primary_contact: "formatjsproject@gmail.com"
main_repo: "https://github.com/formatjs/formatjs"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - none
