homepage: "https://github.com/nasa/spacewasm"
language: rust
primary_contact: "andrei.tumbar@jpl.nasa.gov"
auto_ccs:
  - "haoda.wang@jpl.nasa.gov"
  - "steven.myint@jpl.nasa.gov"
architectures:
  - i386
  - x86_64
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
fuzzing_engines:
  - libfuzzer
main_repo: 'https://github.com/nasa/spacewasm.git'
