homepage: "https://www.iana.org/time-zones"
language: c
primary_contact: "tz@iana.org"
main_repo: "https://github.com/eggert/tz"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
auto_ccs:
  - "tz@iana.org"
