homepage: "https://www.wolfssl.com/wolfssh/"
language: c
main_repo: "https://github.com/wolfSSL/wolfssh"
primary_contact: "john@wolfssl.com"
auto_ccs:
- "david@adalogics.com"
base_os_version: ubuntu-24-04
