homepage: "https://github.com/Open-Cascade-SAS/OCCT"
language: c++
primary_contact: "shravankumarsheri39@gmail.com"
auto_ccs:
  - "shravankumarsheri39@gmail.com"
main_repo: "https://github.com/Open-Cascade-SAS/OCCT.git"
file_github_issue: true
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
vendor_ccs: []
