homepage: "https://github.com/aquasecurity/trivy"
language: go
primary_contact: "security@aquasec.com"
main_repo: "https://github.com/aquasecurity/trivy"
sanitizers: [address, memory]
fuzzing_engines: [libfuzzer]
