fuzzing_engines:
- libfuzzer
homepage: https://docutils.sourceforge.io
language: python
main_repo: https://svn.code.sf.net/p/docutils/code/trunk
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
