homepage: "https://tmux.github.io/"
language: c
primary_contact: "nicholas.marriott@gmail.com"
main_repo: "https://github.com/tmux/tmux.git"

sanitizers:
  - address
  - undefined

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
