homepage: "https://github.com/cyberviser/Hancock"
language: python
primary_contact: "0ai@cyberviserai.com"
auto_ccs:
  - "cyberviser@proton.me"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
main_repo: "https://github.com/cyberviser/Hancock"
