homepage: "https://developers.google.com/speed/webp"
language: c++
primary_contact: "webp-discuss@chromium.org"
auto_ccs:
  - "jzern@google.com"
  - "urvabara@google.com"
main_repo: "https://chromium.googlesource.com/webm/libwebp"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
