homepage: "https://github.com/openbmc/pam-ipmi"
language: c
primary_contact: "javanlacerda@google.com"
auto_ccs:
  - "pedroysb@google.com"
  - "cloud-ti-fuzzing+bugs@google.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
main_repo: "https://github.com/openbmc/pam-ipmi"
