homepage: "https://microsoft.github.io/presidio"
language: python
primary_contact: "avishay.balter@gmail.com"
auto_ccs:
  - presidio@microsoft.com
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
main_repo: "https://github.com/microsoft/presidio"  