homepage: "https://rapidjson.org"
language: c++
primary_contact: "miloyip@gmail.com"
main_repo: "https://github.com/Tencent/rapidjson.git"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
